name: 🔄 Sync Secrets

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main

jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [foo, bar]

    environment: ${{ matrix.environment }}

    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v2

    - name: 🐍 Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 🔐 Run secrets sync script
      env:
        MY_APP_ID: ${{ secrets.MY_APP_ID }}
        MY_APP_SECRET: ${{ secrets.MY_APP_SECRET }}
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        ENVIRONMENT: ${{ matrix.environment }}
        MY_APP_ID_BAR: ${{ secrets.MY_APP_ID_BAR }}
        MY_APP_SECRET_BAR: ${{ secrets.MY_APP_SECRET_BAR }}
        MY_APP_ID_FOO: ${{ secrets.MY_APP_ID_FOO }}
        MY_APP_SECRET_FOO: ${{ secrets.MY_APP_SECRET_FOO }}
      run: |
        python scripts/secrets_sync.py
