name: Sync Secrets

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main

jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    environment: foo

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run secrets sync script
      env:
        MY_APP_ID: ${{ secrets.MY_APP_ID }}
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        python scripts/secrets_sync.py
